### ISSUE TITLE
Android Project

### ISSUE THREAD

**Issue by vedovelli** [tralves/weex-todo-list#1]
Hi!

I'm not an Android Developer. I have Android Studio installed (what an ugly piece of software!) and I tried to open the provided project on /android folder, but I couldn't locate the right file to open. Trying to load the project folder didn't help either.

Could you provide more instructions on your README?! Thanks!

Vedovelli

**Comment by tralves** [comment]
Hi!

Please see the note I added. I hope it helps!
Also, if you think Android Studio is ugly, you probably never had to work with Eclipse 😛 

Tiago

**Comment by vedovelli** [comment]
Thanks for the note! I'm very acquainted with Eclipse cause I used to be a Flex developer back in 2007! =D
