### ISSUE TITLE
File TodosView.vue syntax error

### ISSUE THREAD

**Issue by tonyyls** [tralves/weex-todo-list#2]
hi, i have clone this project, and  npm run dev, find that:
File TodosView.vue syntax error:
tag <div> has no matching end tag.

**Comment by ckdlbc** [comment]
![image](https://cloud.githubusercontent.com/assets/20680413/24282318/b894daae-1099-11e7-9cb8-b0c66e75cd0e.png)

**Comment by ckdlbc** [comment]
![image](https://cloud.githubusercontent.com/assets/20680413/24282328/c3ca5c3c-1099-11e7-9ecc-1922bb87aa65.png)

**Comment by tralves** [comment]
@tonyyls My apologies. I must have missed this issue.
@ckdlbc Thanks for pointing the bug!
